version: '3.8'

networks:
  serving_prod_net:
    external: true

services:
  rag:
    container_name: rag-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    # lit le le fichier .env pour remplir automatiquement
    env_file:
      - ../.env
    environment:
      PORT: "8083"
      HOST: "0.0.0.0"
    networks:
      - serving_prod_net